/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_AuthorizationMethod_H_
#define	_AuthorizationMethod_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AuthorizationMethod {
	AuthorizationMethod_eim	= 0,
	AuthorizationMethod_pnc_2	= 1,
	AuthorizationMethod_pnc_20	= 2
} e_AuthorizationMethod;

/* AuthorizationMethod */
typedef long	 AuthorizationMethod_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AuthorizationMethod_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AuthorizationMethod;
extern const asn_INTEGER_specifics_t asn_SPC_AuthorizationMethod_specs_1;
asn_struct_free_f AuthorizationMethod_free;
asn_struct_print_f AuthorizationMethod_print;
asn_constr_check_f AuthorizationMethod_constraint;
ber_type_decoder_f AuthorizationMethod_decode_ber;
der_type_encoder_f AuthorizationMethod_encode_der;
xer_type_decoder_f AuthorizationMethod_decode_xer;
xer_type_encoder_f AuthorizationMethod_encode_xer;
jer_type_encoder_f AuthorizationMethod_encode_jer;
oer_type_decoder_f AuthorizationMethod_decode_oer;
oer_type_encoder_f AuthorizationMethod_encode_oer;
per_type_decoder_f AuthorizationMethod_decode_uper;
per_type_encoder_f AuthorizationMethod_encode_uper;
per_type_decoder_f AuthorizationMethod_decode_aper;
per_type_encoder_f AuthorizationMethod_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AuthorizationMethod_H_ */
#include <asn_internal.h>
