/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_BasicSignaling_H_
#define	_BasicSignaling_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BasicSignalingProtocol.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BasicSignaling */
typedef struct BasicSignaling {
	A_SEQUENCE_OF(BasicSignalingProtocol_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicSignaling_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicSignaling;

#ifdef __cplusplus
}
#endif

#endif	/* _BasicSignaling_H_ */
#include <asn_internal.h>
