/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_BasicSignalingProtocol_H_
#define	_BasicSignalingProtocol_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BasicSignalingProtocol {
	BasicSignalingProtocol_iec61851_1_ED2	= 0,
	BasicSignalingProtocol_iec61851_1_ED3	= 1,
	BasicSignalingProtocol_iec61851_23_ED1	= 2,
	BasicSignalingProtocol_iec61851_23_ED2	= 3
} e_BasicSignalingProtocol;

/* BasicSignalingProtocol */
typedef long	 BasicSignalingProtocol_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_BasicSignalingProtocol_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_BasicSignalingProtocol;
extern const asn_INTEGER_specifics_t asn_SPC_BasicSignalingProtocol_specs_1;
asn_struct_free_f BasicSignalingProtocol_free;
asn_struct_print_f BasicSignalingProtocol_print;
asn_constr_check_f BasicSignalingProtocol_constraint;
ber_type_decoder_f BasicSignalingProtocol_decode_ber;
der_type_encoder_f BasicSignalingProtocol_encode_der;
xer_type_decoder_f BasicSignalingProtocol_decode_xer;
xer_type_encoder_f BasicSignalingProtocol_encode_xer;
jer_type_encoder_f BasicSignalingProtocol_encode_jer;
oer_type_decoder_f BasicSignalingProtocol_decode_oer;
oer_type_encoder_f BasicSignalingProtocol_encode_oer;
per_type_decoder_f BasicSignalingProtocol_decode_uper;
per_type_encoder_f BasicSignalingProtocol_encode_uper;
per_type_decoder_f BasicSignalingProtocol_decode_aper;
per_type_encoder_f BasicSignalingProtocol_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _BasicSignalingProtocol_H_ */
#include <asn_internal.h>
