/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_ChargingInterface_H_
#define	_ChargingInterface_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChargingInterface {
	ChargingInterface_nacs	= 0,
	ChargingInterface_ccs1	= 1,
	ChargingInterface_ccs2	= 2,
	ChargingInterface_chademo	= 3,
	ChargingInterface_chaoji	= 4,
	ChargingInterface_type_1	= 5,
	ChargingInterface_type_2	= 6,
	ChargingInterface_mcs	= 7
} e_ChargingInterface;

/* ChargingInterface */
typedef long	 ChargingInterface_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChargingInterface;
asn_struct_free_f ChargingInterface_free;
asn_struct_print_f ChargingInterface_print;
asn_constr_check_f ChargingInterface_constraint;
ber_type_decoder_f ChargingInterface_decode_ber;
der_type_encoder_f ChargingInterface_encode_der;
xer_type_decoder_f ChargingInterface_decode_xer;
xer_type_encoder_f ChargingInterface_encode_xer;
jer_type_encoder_f ChargingInterface_encode_jer;
oer_type_decoder_f ChargingInterface_decode_oer;
oer_type_encoder_f ChargingInterface_encode_oer;
per_type_decoder_f ChargingInterface_decode_uper;
per_type_encoder_f ChargingInterface_encode_uper;
per_type_decoder_f ChargingInterface_decode_aper;
per_type_encoder_f ChargingInterface_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ChargingInterface_H_ */
#include <asn_internal.h>
