/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#include "ConductiveChargingInterfaceLimitations.h"

static asn_TYPE_member_t asn_MBR_ConductiveChargingInterfaceLimitations_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConductiveChargingInterfaceLimitations, maximumContactorTemperature),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maximumContactorTemperature"
		},
};
static const ber_tlv_tag_t asn_DEF_ConductiveChargingInterfaceLimitations_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ConductiveChargingInterfaceLimitations_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* maximumContactorTemperature */
};
static asn_SEQUENCE_specifics_t asn_SPC_ConductiveChargingInterfaceLimitations_specs_1 = {
	sizeof(struct ConductiveChargingInterfaceLimitations),
	offsetof(struct ConductiveChargingInterfaceLimitations, _asn_ctx),
	asn_MAP_ConductiveChargingInterfaceLimitations_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ConductiveChargingInterfaceLimitations = {
	"ConductiveChargingInterfaceLimitations",
	"ConductiveChargingInterfaceLimitations",
	&asn_OP_SEQUENCE,
	asn_DEF_ConductiveChargingInterfaceLimitations_tags_1,
	sizeof(asn_DEF_ConductiveChargingInterfaceLimitations_tags_1)
		/sizeof(asn_DEF_ConductiveChargingInterfaceLimitations_tags_1[0]), /* 1 */
	asn_DEF_ConductiveChargingInterfaceLimitations_tags_1,	/* Same as above */
	sizeof(asn_DEF_ConductiveChargingInterfaceLimitations_tags_1)
		/sizeof(asn_DEF_ConductiveChargingInterfaceLimitations_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ConductiveChargingInterfaceLimitations_1,
	1,	/* Elements count */
	&asn_SPC_ConductiveChargingInterfaceLimitations_specs_1	/* Additional specs */
};

