/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_DCChargingLimits_H_
#define	_DCChargingLimits_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DCChargingLimits */
typedef struct DCChargingLimits {
	long	 maximumVoltage;
	long	 minimumVoltage;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DCChargingLimits_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DCChargingLimits;

#ifdef __cplusplus
}
#endif

#endif	/* _DCChargingLimits_H_ */
#include <asn_internal.h>
