/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_EMSPIdentifier_H_
#define	_EMSPIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EMSPIdentifier */
typedef OCTET_STRING_t	 EMSPIdentifier_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EMSPIdentifier_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EMSPIdentifier;
asn_struct_free_f EMSPIdentifier_free;
asn_struct_print_f EMSPIdentifier_print;
asn_constr_check_f EMSPIdentifier_constraint;
ber_type_decoder_f EMSPIdentifier_decode_ber;
der_type_encoder_f EMSPIdentifier_encode_der;
xer_type_decoder_f EMSPIdentifier_decode_xer;
xer_type_encoder_f EMSPIdentifier_encode_xer;
jer_type_encoder_f EMSPIdentifier_encode_jer;
oer_type_decoder_f EMSPIdentifier_decode_oer;
oer_type_encoder_f EMSPIdentifier_encode_oer;
per_type_decoder_f EMSPIdentifier_decode_uper;
per_type_encoder_f EMSPIdentifier_encode_uper;
per_type_decoder_f EMSPIdentifier_decode_aper;
per_type_encoder_f EMSPIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EMSPIdentifier_H_ */
#include <asn_internal.h>
