/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_EnergyTransferMode_H_
#define	_EnergyTransferMode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EnergyTransferMode {
	EnergyTransferMode_dc	= 0,
	EnergyTransferMode_dc_bpt	= 1,
	EnergyTransferMode_ac	= 2,
	EnergyTransferMode_ac_bpt	= 3
} e_EnergyTransferMode;

/* EnergyTransferMode */
typedef long	 EnergyTransferMode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EnergyTransferMode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EnergyTransferMode;
extern const asn_INTEGER_specifics_t asn_SPC_EnergyTransferMode_specs_1;
asn_struct_free_f EnergyTransferMode_free;
asn_struct_print_f EnergyTransferMode_print;
asn_constr_check_f EnergyTransferMode_constraint;
ber_type_decoder_f EnergyTransferMode_decode_ber;
der_type_encoder_f EnergyTransferMode_encode_der;
xer_type_decoder_f EnergyTransferMode_decode_xer;
xer_type_encoder_f EnergyTransferMode_encode_xer;
jer_type_encoder_f EnergyTransferMode_encode_jer;
oer_type_decoder_f EnergyTransferMode_decode_oer;
oer_type_encoder_f EnergyTransferMode_encode_oer;
per_type_decoder_f EnergyTransferMode_decode_uper;
per_type_encoder_f EnergyTransferMode_encode_uper;
per_type_decoder_f EnergyTransferMode_decode_aper;
per_type_encoder_f EnergyTransferMode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EnergyTransferMode_H_ */
#include <asn_internal.h>
