/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_EVCharacteristics_H_
#define	_EVCharacteristics_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EVCharacteristics */
typedef struct EVCharacteristics {
	OCTET_STRING_t	*vehicleIdentificationNumber;	/* OPTIONAL */
	UTF8String_t	*evccSoftwareVersion;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EVCharacteristics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EVCharacteristics;

#ifdef __cplusplus
}
#endif

#endif	/* _EVCharacteristics_H_ */
#include <asn_internal.h>
