/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_Extensions_H_
#define	_Extensions_H_


#include <asn_application.h>

/* Including external dependencies */
#include "StandardizedExtensions.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExternalExtensions;

/* Extensions */
typedef struct Extensions {
	StandardizedExtensions_t	 standardized;
	struct ExternalExtensions	*external;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Extensions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Extensions;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExternalExtensions.h"

#endif	/* _Extensions_H_ */
#include <asn_internal.h>
