/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_ExternalExtension_H_
#define	_ExternalExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <BOOLEAN.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExternalExtension */
typedef struct ExternalExtension {
	OBJECT_IDENTIFIER_t	 externalExtensionID;
	BOOLEAN_t	*critical;	/* DEFAULT TRUE */
	OCTET_STRING_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExternalExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExternalExtension;
extern asn_SEQUENCE_specifics_t asn_SPC_ExternalExtension_specs_1;
extern asn_TYPE_member_t asn_MBR_ExternalExtension_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ExternalExtension_H_ */
#include <asn_internal.h>
