/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_HighLevelCommunicationTuple_H_
#define	_HighLevelCommunicationTuple_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HLCProtocol.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SecurityProfileTuple;

/* HighLevelCommunicationTuple */
typedef struct HighLevelCommunicationTuple {
	HLCProtocol_t	 hlcProtocol;
	struct securityProfileTuple {
		A_SEQUENCE_OF(struct SecurityProfileTuple) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} securityProfileTuple;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HighLevelCommunicationTuple_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HighLevelCommunicationTuple;
extern asn_SEQUENCE_specifics_t asn_SPC_HighLevelCommunicationTuple_specs_1;
extern asn_TYPE_member_t asn_MBR_HighLevelCommunicationTuple_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SecurityProfileTuple.h"

#endif	/* _HighLevelCommunicationTuple_H_ */
#include <asn_internal.h>
