/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_HighLevelCommunication_H_
#define	_HighLevelCommunication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct HighLevelCommunicationTuple;

/* HighLevelCommunication */
typedef struct HighLevelCommunication {
	A_SEQUENCE_OF(struct HighLevelCommunicationTuple) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HighLevelCommunication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HighLevelCommunication;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "HighLevelCommunicationTuple.h"

#endif	/* _HighLevelCommunication_H_ */
#include <asn_internal.h>
