/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_HLCProtocol_H_
#define	_HLCProtocol_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HLCProtocol {
	HLCProtocol_din_spec_70121_2014	= 0,
	HLCProtocol_iso_15118_2_2014	= 1,
	HLCProtocol_iso_15118_20_2022	= 2,
	HLCProtocol_sae_j2847_2_202309	= 3
} e_HLCProtocol;

/* HLCProtocol */
typedef long	 HLCProtocol_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_HLCProtocol_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_HLCProtocol;
extern const asn_INTEGER_specifics_t asn_SPC_HLCProtocol_specs_1;
asn_struct_free_f HLCProtocol_free;
asn_struct_print_f HLCProtocol_print;
asn_constr_check_f HLCProtocol_constraint;
ber_type_decoder_f HLCProtocol_decode_ber;
der_type_encoder_f HLCProtocol_encode_der;
xer_type_decoder_f HLCProtocol_decode_xer;
xer_type_encoder_f HLCProtocol_encode_xer;
jer_type_encoder_f HLCProtocol_encode_jer;
oer_type_decoder_f HLCProtocol_decode_oer;
oer_type_encoder_f HLCProtocol_encode_oer;
per_type_decoder_f HLCProtocol_decode_uper;
per_type_encoder_f HLCProtocol_encode_uper;
per_type_decoder_f HLCProtocol_decode_aper;
per_type_encoder_f HLCProtocol_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HLCProtocol_H_ */
#include <asn_internal.h>
