/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_IPv6Socket_H_
#define	_IPv6Socket_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IPv6Socket */
typedef struct IPv6Socket {
	OCTET_STRING_t	 ipv6Address;
	OCTET_STRING_t	 tcpPort;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IPv6Socket_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IPv6Socket;

#ifdef __cplusplus
}
#endif

#endif	/* _IPv6Socket_H_ */
#include <asn_internal.h>
