/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_SecurityProfile_H_
#define	_SecurityProfile_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecurityProfile {
	SecurityProfile_tcpOnly	= 0,
	SecurityProfile_tls12_server	= 2,
	SecurityProfile_tls13_mutual	= 20
} e_SecurityProfile;

/* SecurityProfile */
typedef long	 SecurityProfile_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SecurityProfile_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SecurityProfile;
extern const asn_INTEGER_specifics_t asn_SPC_SecurityProfile_specs_1;
asn_struct_free_f SecurityProfile_free;
asn_struct_print_f SecurityProfile_print;
asn_constr_check_f SecurityProfile_constraint;
ber_type_decoder_f SecurityProfile_decode_ber;
der_type_encoder_f SecurityProfile_encode_der;
xer_type_decoder_f SecurityProfile_decode_xer;
xer_type_encoder_f SecurityProfile_encode_xer;
jer_type_encoder_f SecurityProfile_encode_jer;
oer_type_decoder_f SecurityProfile_decode_oer;
oer_type_encoder_f SecurityProfile_encode_oer;
per_type_decoder_f SecurityProfile_decode_uper;
per_type_encoder_f SecurityProfile_encode_uper;
per_type_decoder_f SecurityProfile_decode_aper;
per_type_encoder_f SecurityProfile_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityProfile_H_ */
#include <asn_internal.h>
