/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#include "SecurityProfile.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_SecurityProfile_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_SecurityProfile_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_SecurityProfile_value2enum_1[] = {
	{ 0,	7,	"tcpOnly" },
	{ 2,	12,	"tls12-server" },
	{ 20,	12,	"tls13-mutual" }
};
static const unsigned int asn_MAP_SecurityProfile_enum2value_1[] = {
	0,	/* tcpOnly(0) */
	1,	/* tls12-server(2) */
	2	/* tls13-mutual(20) */
};
const asn_INTEGER_specifics_t asn_SPC_SecurityProfile_specs_1 = {
	asn_MAP_SecurityProfile_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_SecurityProfile_enum2value_1,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_SecurityProfile_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_SecurityProfile = {
	"SecurityProfile",
	"SecurityProfile",
	&asn_OP_NativeEnumerated,
	asn_DEF_SecurityProfile_tags_1,
	sizeof(asn_DEF_SecurityProfile_tags_1)
		/sizeof(asn_DEF_SecurityProfile_tags_1[0]), /* 1 */
	asn_DEF_SecurityProfile_tags_1,	/* Same as above */
	sizeof(asn_DEF_SecurityProfile_tags_1)
		/sizeof(asn_DEF_SecurityProfile_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_SecurityProfile_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_SecurityProfile_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_SecurityProfile_specs_1	/* Additional specs */
};

