/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_SecurityProfileTuple_H_
#define	_SecurityProfileTuple_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SecurityProfile.h"
#include "AuthorizationMethod.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "EnergyTransferMode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SecurityProfileTuple */
typedef struct SecurityProfileTuple {
	SecurityProfile_t	 securityProfile;
	struct authorizationMethod {
		A_SEQUENCE_OF(AuthorizationMethod_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} authorizationMethod;
	struct energyTransferMode {
		A_SEQUENCE_OF(EnergyTransferMode_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} energyTransferMode;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityProfileTuple_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityProfileTuple;
extern asn_SEQUENCE_specifics_t asn_SPC_SecurityProfileTuple_specs_1;
extern asn_TYPE_member_t asn_MBR_SecurityProfileTuple_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityProfileTuple_H_ */
#include <asn_internal.h>
