/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#include "StandardizedExtension.h"

asn_TYPE_member_t asn_MBR_StandardizedExtension_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct StandardizedExtension, extensionID),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"extensionID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StandardizedExtension, extensionValue),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"extensionValue"
		},
};
static const ber_tlv_tag_t asn_DEF_StandardizedExtension_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_StandardizedExtension_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* extensionID */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 } /* extensionValue */
};
asn_SEQUENCE_specifics_t asn_SPC_StandardizedExtension_specs_1 = {
	sizeof(struct StandardizedExtension),
	offsetof(struct StandardizedExtension, _asn_ctx),
	asn_MAP_StandardizedExtension_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_StandardizedExtension = {
	"StandardizedExtension",
	"StandardizedExtension",
	&asn_OP_SEQUENCE,
	asn_DEF_StandardizedExtension_tags_1,
	sizeof(asn_DEF_StandardizedExtension_tags_1)
		/sizeof(asn_DEF_StandardizedExtension_tags_1[0]), /* 1 */
	asn_DEF_StandardizedExtension_tags_1,	/* Same as above */
	sizeof(asn_DEF_StandardizedExtension_tags_1)
		/sizeof(asn_DEF_StandardizedExtension_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_StandardizedExtension_1,
	2,	/* Elements count */
	&asn_SPC_StandardizedExtension_specs_1	/* Additional specs */
};

