/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_StandardizedExtension_H_
#define	_StandardizedExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* StandardizedExtension */
typedef struct StandardizedExtension {
	long	 extensionID;
	OCTET_STRING_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StandardizedExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StandardizedExtension;
extern asn_SEQUENCE_specifics_t asn_SPC_StandardizedExtension_specs_1;
extern asn_TYPE_member_t asn_MBR_StandardizedExtension_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _StandardizedExtension_H_ */
#include <asn_internal.h>
