/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO15118-200"
 * 	found in "esdp_extensions_new.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_StandardizedExtensions_H_
#define	_StandardizedExtensions_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct StandardizedExtension;

/* StandardizedExtensions */
typedef struct StandardizedExtensions {
	A_SEQUENCE_OF(struct StandardizedExtension) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StandardizedExtensions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StandardizedExtensions;
extern asn_SET_OF_specifics_t asn_SPC_StandardizedExtensions_specs_1;
extern asn_TYPE_member_t asn_MBR_StandardizedExtensions_1[1];
extern asn_per_constraints_t asn_PER_type_StandardizedExtensions_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "StandardizedExtension.h"

#endif	/* _StandardizedExtensions_H_ */
#include <asn_internal.h>
